language: node_js
node_js: node
branches:
  only:
  - master
install:
- npm install
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    secure: jtyoGcFEFUFNm5DAZmOWAlUF6TAvW9XZM12McOj5dpkwfTt6z++CLpBSSR3lVJLhj9Ff7DQ4N7leBwxK99NV+BXG8HS/DauCEbRZ1RWuaKXaDwKPU4pazMwaJfCTLF1WC02oFH7oPTOYe21wQzJyBTkaC/LOptPddQc4k1LEI8KWkqR1unFgDdFg5u7vgwIhZRPDERYYj+N20Vm8xIkeaEmv95McR9pGGDFAA7KQoAPgNoIPGgJEJWeDm/ATTwd5/AMWC44AjGRJXYlJBuczJASLejB2SoG/gGMsxAeNzFr6hzBjB5E/tZ/L5FQzpLuPhFOxEXOgmiJ69pRBUPQ0njCdlKg9w1UnAR0Q/XBTbS/9TzgZHdkqTZOxu8guZObtMg804vrRRW8vnFM0wMcX/wcD505QpF6Ff/TlmZN/xb3RA0HC5cxNSjtkruXm/LoRS3Rlf/eYH9K4S1wVISK2WFupfznBrS2eu6xmr3+rGfp6G6LSYNG3FEQD+Cg1ZKj2DMJBD5Gz/MzqjfNwTaWF19fiZ3e02KswQs7HLXHdhh+0N4KJaFE6CrQdxTvked9TBkZHw3s2hdZQjlY99IYBl2hMmRMathmmT/mpd1JFQeiLk0ZU22yqT9kwsg/FgKo3aQZvtPVX0wJ5QSfzMESrEZdhe4jCXpsTRFw1IRsSg+4=